### ISSUE TITLE
Winbind integration

### ISSUE THREAD

**Issue by Adphi** [skarnet/nsss#2]
I am looking for a way to get domain authentication to work on Alpine.
So far, I've managed to join the domain using winbind, but I can't find a way to make nss winbind work.
I have tried unsuccessfully with nscd: `getent passwd` and others work but not `login`.

How can I do this with nsss?

**Comment by skarnet** [comment]
I don't know how winbind works, but if you didn't manage to make login work with nscd, there isn't much that nsss is going to do for you. In order to help, nsss needs to be integrated in the whole distribution, and for now, Alpine isn't being built with nsss (although it may be the plan in the future).

`login` is a special case among all tools because it's implemented by busybox, and getting busybox to work with various improvements has historically been a challenge... it's also on the list of things to change within Alpine, but it will require serious work.

Sorry I can't help you much more.

**Comment by Adphi** [comment]
Thank you for responding so quickly ! 
I'll take a look at busybox login implementation and alternatives.

**Comment by Adphi** [comment]
@skarnet Thank you so much for the `login`	lead. I got it working with _nscd_ the one provided by _shadow-login_ 😁
